name: prix
version: 0.0.0
github: "vst/prix"
license: MIT
author: "Vehbi Sinan Tunalioglu"
maintainer: "vst@vsthost.com"
copyright: "Copyright (c) 2025 Vehbi Sinan Tunalioglu"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/vst/prix#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror
    - -Wunused-packages
  dependencies:
    - aeson
    - autodocodec
    - bytestring
    - githash
    - optparse-applicative
    - path
    - path-io
    - string-interpolate
    - template-haskell
    - text
    - time
    - typed-process
    - unordered-containers
    - yaml

executables:
  prix:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Werror
      - -Wunused-packages
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - prix

tests:
  prix-test:
    main: Spec.hs
    source-dirs: test/spec
    ghc-options:
      - -Wall
      - -Werror
      - -Wunused-packages
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies: []

  prix-doctest:
    main: doctest.hs
    source-dirs: test/doctest
    ghc-options:
      - -Wall
      - -Werror
      - -threaded
    dependencies:
      - prix
      - doctest
