mutation ($issueId: ID!, $title: String!, $body: String, $issueTypeId: ID) {
  updateIssue(
    input: {
      id: $issueId
      title: $title
      body: $body
      issueTypeId: $issueTypeId
    }
  ) {
    issue {
      id
    }
  }
}
